codecov:
  archive:
    uploads: yes
  bot: mdabrowski1990

coverage:
  range: 80...100
  round: down
  precision: 2
  status:
    project:
      default:
        target: 100%
      unit-tests:
        target: 100%
        flags:
          - unit-tests
      integration-tests:
        target: 80%
        flags:
          - integration-tests

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
