codecov:
  archive:
    uploads: false

coverage:
  range: 80...100
  round: down
  precision: 2
  status:
    project:
      default:
        target: 100%
      unit-tests:
        target: 100%
        flags:
          - unit-tests
      unit-tests-branch:
        flags:
          - unit-tests-branch
      integration-tests:
        target: 80%
        flags:
          - integration-tests
      integration-tests-branch:
        flags:
          - integration-tests-branch

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
