# Required
version: 2


# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_install:
      - whoami
      - sudo apg-get update
      - sudo apg-get install graphviz


      # Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  fail_on_warning: true
  configuration: docs/source/conf.py


# Optionally build your docs in additional formats such as PDF
formats:
  - htmlzip
  - pdf


# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - requirements: docs/requirements_for_docs.txt
    - requirements: requirements.txt
