# Configuration of Travis-CI and Coveralls that are used for build verification and coverage assesment.

language: python

python:
  - "3.9"

install:
  - "pip install -r requirements.txt"
  - "pip install -r tests/requirements_for_software_tests.txt"
  - "pip install coveralls"

script:
  - "coverage run --source=uds -m pytest tests/software_tests/"
 
after_sucess: coveralls
