codecov:
  archive:
    uploads: yes
  bot: mdabrowski1990


coverage:
  range: 80...100
  round: nearest
  precision: 2


comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
