"""Data Records definitions for basic Translator."""

from .other import (
    CONDITIONAL_POWER_DOWN_TIME,
    P2_EXT_SERVER_MAX,
    P2_SERVER_MAX,
    POWER_DOWN_TIME,
    SESSION_PARAMETER_RECORD,
)
from .sub_functions import (
    DIAGNOSTIC_SESSION_CONTROL_SUB_FUNCTION,
    DIAGNOSTIC_SESSION_TYPE,
    ECU_RESET_SUB_FUNCTION,
    RESET_TYPE,
    SPRMIB,
    TESTER_PRESENT_SUB_FUNCTION,
    ZERO_SUB_FUNCTION,
)
