"""Data Records definitions for basic Translator."""

from .other import (
    CONDITIONAL_POWER_DOWN_TIME,
    DTC_COUNT,
    DTC_FORMAT_IDENTIFIER,
    DTC_STATUS_AVAILABILITY_MASK,
    DTC_STATUS_MASK,
    GROUP_OF_DTC,
    MEMORY_SELECTION,
    MULTIPLE_DTC_AND_STATUS_RECORDS,
    P2_EXT_SERVER_MAX,
    P2_SERVER_MAX,
    POWER_DOWN_TIME,
    SESSION_PARAMETER_RECORD,
OPTIONAL_SINGLE_DTC_AND_STATUS_RECORD,
)
from .sub_functions import (
    DIAGNOSTIC_SESSION_CONTROL_SUB_FUNCTION,
    DIAGNOSTIC_SESSION_TYPE,
    DIAGNOSTIC_SESSIONS_MAPPING,
    ECU_RESET_SUB_FUNCTION,
    READ_DTC_INFORMATION_SUB_FUNCTION_2013,
    READ_DTC_INFORMATION_SUB_FUNCTION_2020,
    REPORT_TYPE_2013,
    REPORT_TYPE_2020,
    REPORT_TYPES_MAPPING_2013,
    REPORT_TYPES_MAPPING_2020,
    RESET_TYPE,
    RESET_TYPES_MAPPING,
    SPRMIB,
    TESTER_PRESENT_SUB_FUNCTION,
    ZERO_SUB_FUNCTION,
)
