"""Data Records definitions for basic Translator."""

from .other import (
    CONDITIONAL_POWER_DOWN_TIME,
    GROUP_OF_DTC,
    MEMORY_SELECTION,
    P2_EXT_SERVER_MAX,
    P2_SERVER_MAX,
    POWER_DOWN_TIME,
    SESSION_PARAMETER_RECORD,
)
from .sub_functions import (
    DIAGNOSTIC_SESSION_CONTROL_SUB_FUNCTION,
    DIAGNOSTIC_SESSION_TYPE,
    DIAGNOSTIC_SESSIONS_MAPPING,
    ECU_RESET_SUB_FUNCTION_2013,
    ECU_RESET_SUB_FUNCTION_2020,
    RESET_TYPE_2013,
    RESET_TYPE_2020,
    RESET_TYPES_MAPPING_2013,
    RESET_TYPES_MAPPING_2020,
    SPRMIB,
    TESTER_PRESENT_SUB_FUNCTION,
    ZERO_SUB_FUNCTION,
)
