"""Translation for ReadDTCInformation (SID 0x19) service."""

__all__ = ["READ_DTC_INFORMATION", "READ_DTC_INFORMATION_2020", "READ_DTC_INFORMATION_2013"]

from uds.message import RequestSID

from ..data_record import ConditionalMappingDataRecord
from ..data_record_definitions import (
    DTC_STATUS_MASK,
    READ_DTC_INFORMATION_SUB_FUNCTION_2013,
    READ_DTC_INFORMATION_SUB_FUNCTION_2020,
DTC_STATUS_AVAILABILITY_MASK, DTC_FORMAT_IDENTIFIER, DTC_COUNT, MULTIPLE_DTC_AND_STATUS_RECORDS, OPTIONAL_SINGLE_DTC_AND_STATUS_RECORD
)
from ..service import Service

REQUEST_CONTINUATION_MAPPING_2013 = {
    0x01: (DTC_STATUS_MASK,),
    0x02: (DTC_STATUS_MASK,),
    # TODO
}
REQUEST_CONTINUATION_MAPPING_2020 = {
    0x01: (DTC_STATUS_MASK,),
    0x02: (DTC_STATUS_MASK,),
    # TODO
}

RESPONSE_CONTINUATION_MAPPING_2013 = {
    0x01: (DTC_STATUS_AVAILABILITY_MASK, DTC_FORMAT_IDENTIFIER, DTC_COUNT),
    0x02: (DTC_STATUS_AVAILABILITY_MASK, MULTIPLE_DTC_AND_STATUS_RECORDS),
    0x07: (DTC_STATUS_AVAILABILITY_MASK, DTC_FORMAT_IDENTIFIER, DTC_COUNT),
    0x0A: (DTC_STATUS_AVAILABILITY_MASK, MULTIPLE_DTC_AND_STATUS_RECORDS),
    0x0B: (DTC_STATUS_AVAILABILITY_MASK, OPTIONAL_SINGLE_DTC_AND_STATUS_RECORD),
    0x0C: (DTC_STATUS_AVAILABILITY_MASK, OPTIONAL_SINGLE_DTC_AND_STATUS_RECORD),
    0x0D: (DTC_STATUS_AVAILABILITY_MASK, OPTIONAL_SINGLE_DTC_AND_STATUS_RECORD),
    0x0E: (DTC_STATUS_AVAILABILITY_MASK, OPTIONAL_SINGLE_DTC_AND_STATUS_RECORD),
    0x0F: (DTC_STATUS_AVAILABILITY_MASK, MULTIPLE_DTC_AND_STATUS_RECORDS),
    0x11: (DTC_STATUS_AVAILABILITY_MASK, DTC_FORMAT_IDENTIFIER, DTC_COUNT),
    0x12: (DTC_STATUS_AVAILABILITY_MASK, DTC_FORMAT_IDENTIFIER, DTC_COUNT),
    0x13: (DTC_STATUS_AVAILABILITY_MASK, MULTIPLE_DTC_AND_STATUS_RECORDS),
    0x15: (DTC_STATUS_AVAILABILITY_MASK, MULTIPLE_DTC_AND_STATUS_RECORDS),
    # TODO
}
RESPONSE_CONTINUATION_MAPPING_2020 = {
    0x01: (DTC_STATUS_AVAILABILITY_MASK, DTC_FORMAT_IDENTIFIER, DTC_COUNT),
    0x02: (DTC_STATUS_AVAILABILITY_MASK, MULTIPLE_DTC_AND_STATUS_RECORDS),
    0x07: (DTC_STATUS_AVAILABILITY_MASK, DTC_FORMAT_IDENTIFIER, DTC_COUNT),
    0x0A: (DTC_STATUS_AVAILABILITY_MASK, MULTIPLE_DTC_AND_STATUS_RECORDS),
    0x0B: (DTC_STATUS_AVAILABILITY_MASK, OPTIONAL_SINGLE_DTC_AND_STATUS_RECORD),
    0x0C: (DTC_STATUS_AVAILABILITY_MASK, OPTIONAL_SINGLE_DTC_AND_STATUS_RECORD),
    0x0D: (DTC_STATUS_AVAILABILITY_MASK, OPTIONAL_SINGLE_DTC_AND_STATUS_RECORD),
    0x0E: (DTC_STATUS_AVAILABILITY_MASK, OPTIONAL_SINGLE_DTC_AND_STATUS_RECORD),
    0x15: (DTC_STATUS_AVAILABILITY_MASK, MULTIPLE_DTC_AND_STATUS_RECORDS),
    # TODO
}

CONDITIONAL_REQUEST_CONTINUATION_2013 = ConditionalMappingDataRecord(mapping=dict(
    **{key: value, key + 0x80: value}
    for key, value in REQUEST_CONTINUATION_MAPPING_2013.items()))
CONDITIONAL_REQUEST_CONTINUATION_2020 =ConditionalMappingDataRecord(mapping=dict(
    **{key: value, key + 0x80: value}
    for key, value in REQUEST_CONTINUATION_MAPPING_2020.items()))

CONDITIONAL_RESPONSE_CONTINUATION_2013 = ConditionalMappingDataRecord(mapping=dict(
    **{key: value, key + 0x80: value}
    for key, value in RESPONSE_CONTINUATION_MAPPING_2013.items()))
CONDITIONAL_RESPONSE_CONTINUATION_2020 = ConditionalMappingDataRecord(mapping=dict(
    **{key: value, key + 0x80: value}
    for key, value in RESPONSE_CONTINUATION_MAPPING_2020.items()))

READ_DTC_INFORMATION_2013 = Service(request_sid=RequestSID.ReadDTCInformation,
                                    request_structure=(READ_DTC_INFORMATION_SUB_FUNCTION_2013,
                                                       CONDITIONAL_REQUEST_CONTINUATION_2013),
                                    response_structure=[READ_DTC_INFORMATION_SUB_FUNCTION_2013,
                                                        CONDITIONAL_RESPONSE_CONTINUATION_2013])
"""Translator for :ref:`ReadDTCInformation <knowledge-base-service-read-dtc-information>` service compatible with 
ISO 14229-1:2013."""

READ_DTC_INFORMATION_2020 = Service(request_sid=RequestSID.ReadDTCInformation,
                                    request_structure=(READ_DTC_INFORMATION_SUB_FUNCTION_2020,
                                                       CONDITIONAL_REQUEST_CONTINUATION_2020),
                                    response_structure=[READ_DTC_INFORMATION_SUB_FUNCTION_2020,
                                                        CONDITIONAL_RESPONSE_CONTINUATION_2020])
"""Translator for :ref:`ReadDTCInformation <knowledge-base-service-read-dtc-information>` service compatible with 
ISO 14229-1:2020."""

READ_DTC_INFORMATION = READ_DTC_INFORMATION_2020
"""Default translator for :ref:`ReadDTCInformation <knowledge-base-service-read-dtc-information>` service."""