"""Translation for RequestFileTransfer (SID 0x38) service."""

__all__ = ["REQUEST_FILE_TRANSFER", "REQUEST_FILE_TRANSFER_2020", "REQUEST_FILE_TRANSFER_2013"]

from uds.message import RequestSID

from ..data_record import ConditionalMappingDataRecord
from ..data_record_definitions import (
    CONDITIONAL_DIR_INFO,
    CONDITIONAL_FILE_AND_PATH_NAME,
    CONDITIONAL_FILE_SIZES,
    CONDITIONAL_FILE_SIZES_OR_DIR_INFO,
    CONDITIONAL_MAX_NUMBER_OF_BLOCK_LENGTH_FILE_TRANSFER,
    DATA_FORMAT_IDENTIFIER,
    FILE_AND_PATH_NAME_LENGTH,
    FILE_POSITION,
    FILE_SIZE_OR_DIR_INFO_PARAMETER_LENGTH,
    FILE_SIZE_PARAMETER_LENGTH,
    LENGTH_FORMAT_IDENTIFIER_FILE_TRANSFER,
    MODE_OF_OPERATION_2013,
    MODE_OF_OPERATION_2020,
)
from ..service import Service

REQUEST_CONTINUATION_MAPPING_2013 = {
    0x01: (FILE_AND_PATH_NAME_LENGTH, CONDITIONAL_FILE_AND_PATH_NAME,
           DATA_FORMAT_IDENTIFIER,
           FILE_SIZE_PARAMETER_LENGTH, CONDITIONAL_FILE_SIZES),
    0x02: (FILE_AND_PATH_NAME_LENGTH, CONDITIONAL_FILE_AND_PATH_NAME),
    0x03: (FILE_AND_PATH_NAME_LENGTH, CONDITIONAL_FILE_AND_PATH_NAME,
           DATA_FORMAT_IDENTIFIER,
           FILE_SIZE_PARAMETER_LENGTH, CONDITIONAL_FILE_SIZES),
    0x04: (FILE_AND_PATH_NAME_LENGTH, CONDITIONAL_FILE_AND_PATH_NAME,
           DATA_FORMAT_IDENTIFIER),
    0x05: (FILE_AND_PATH_NAME_LENGTH, CONDITIONAL_FILE_AND_PATH_NAME),
}
REQUEST_CONTINUATION_MAPPING_2020 = {
    0x01: (FILE_AND_PATH_NAME_LENGTH, CONDITIONAL_FILE_AND_PATH_NAME,
           DATA_FORMAT_IDENTIFIER,
           FILE_SIZE_PARAMETER_LENGTH, CONDITIONAL_FILE_SIZES),
    0x02: (FILE_AND_PATH_NAME_LENGTH, CONDITIONAL_FILE_AND_PATH_NAME),
    0x03: (FILE_AND_PATH_NAME_LENGTH, CONDITIONAL_FILE_AND_PATH_NAME,
           DATA_FORMAT_IDENTIFIER,
           FILE_SIZE_PARAMETER_LENGTH, CONDITIONAL_FILE_SIZES),
    0x04: (FILE_AND_PATH_NAME_LENGTH, CONDITIONAL_FILE_AND_PATH_NAME,
           DATA_FORMAT_IDENTIFIER),
    0x05: (FILE_AND_PATH_NAME_LENGTH, CONDITIONAL_FILE_AND_PATH_NAME),
    0x06: (FILE_AND_PATH_NAME_LENGTH, CONDITIONAL_FILE_AND_PATH_NAME,
           DATA_FORMAT_IDENTIFIER,
           FILE_SIZE_PARAMETER_LENGTH, CONDITIONAL_FILE_SIZES),
}

RESPONSE_CONTINUATION_MAPPING_2013 = {
    0x01: (LENGTH_FORMAT_IDENTIFIER_FILE_TRANSFER, CONDITIONAL_MAX_NUMBER_OF_BLOCK_LENGTH_FILE_TRANSFER,
           DATA_FORMAT_IDENTIFIER),
    0x02: (),
    0x03: (LENGTH_FORMAT_IDENTIFIER_FILE_TRANSFER, CONDITIONAL_MAX_NUMBER_OF_BLOCK_LENGTH_FILE_TRANSFER,
           DATA_FORMAT_IDENTIFIER),
    0x04: (LENGTH_FORMAT_IDENTIFIER_FILE_TRANSFER, CONDITIONAL_MAX_NUMBER_OF_BLOCK_LENGTH_FILE_TRANSFER,
           DATA_FORMAT_IDENTIFIER,
           FILE_SIZE_OR_DIR_INFO_PARAMETER_LENGTH, CONDITIONAL_FILE_SIZES_OR_DIR_INFO),
    0x05: (LENGTH_FORMAT_IDENTIFIER_FILE_TRANSFER, CONDITIONAL_MAX_NUMBER_OF_BLOCK_LENGTH_FILE_TRANSFER,
           DATA_FORMAT_IDENTIFIER,
           FILE_SIZE_OR_DIR_INFO_PARAMETER_LENGTH, CONDITIONAL_DIR_INFO),
}
RESPONSE_CONTINUATION_MAPPING_2020 = {
    0x01: (LENGTH_FORMAT_IDENTIFIER_FILE_TRANSFER, CONDITIONAL_MAX_NUMBER_OF_BLOCK_LENGTH_FILE_TRANSFER,
           DATA_FORMAT_IDENTIFIER),
    0x02: (),
    0x03: (LENGTH_FORMAT_IDENTIFIER_FILE_TRANSFER, CONDITIONAL_MAX_NUMBER_OF_BLOCK_LENGTH_FILE_TRANSFER,
           DATA_FORMAT_IDENTIFIER),
    0x04: (LENGTH_FORMAT_IDENTIFIER_FILE_TRANSFER, CONDITIONAL_MAX_NUMBER_OF_BLOCK_LENGTH_FILE_TRANSFER,
           DATA_FORMAT_IDENTIFIER,
           FILE_SIZE_OR_DIR_INFO_PARAMETER_LENGTH, CONDITIONAL_FILE_SIZES_OR_DIR_INFO),
    0x05: (LENGTH_FORMAT_IDENTIFIER_FILE_TRANSFER, CONDITIONAL_MAX_NUMBER_OF_BLOCK_LENGTH_FILE_TRANSFER,
           DATA_FORMAT_IDENTIFIER,
           FILE_SIZE_OR_DIR_INFO_PARAMETER_LENGTH, CONDITIONAL_DIR_INFO),
    0x06: (LENGTH_FORMAT_IDENTIFIER_FILE_TRANSFER, CONDITIONAL_MAX_NUMBER_OF_BLOCK_LENGTH_FILE_TRANSFER,
           DATA_FORMAT_IDENTIFIER,
           FILE_POSITION),
}

CONDITIONAL_REQUEST_CONTINUATION_2013 = ConditionalMappingDataRecord(mapping=REQUEST_CONTINUATION_MAPPING_2013)
CONDITIONAL_REQUEST_CONTINUATION_2020 = ConditionalMappingDataRecord(mapping=REQUEST_CONTINUATION_MAPPING_2020)

CONDITIONAL_RESPONSE_CONTINUATION_2013 = ConditionalMappingDataRecord(mapping=RESPONSE_CONTINUATION_MAPPING_2013)
CONDITIONAL_RESPONSE_CONTINUATION_2020 = ConditionalMappingDataRecord(mapping=RESPONSE_CONTINUATION_MAPPING_2020)

REQUEST_FILE_TRANSFER_2013 = Service(request_sid=RequestSID.RequestFileTransfer,
                                     request_structure=(MODE_OF_OPERATION_2013,
                                                        CONDITIONAL_REQUEST_CONTINUATION_2013),
                                     response_structure=(MODE_OF_OPERATION_2013,
                                                         CONDITIONAL_RESPONSE_CONTINUATION_2013))
"""Translator for :ref:`RequestFileTransfer <knowledge-base-service-request-file-transfer>` service
compatible with ISO 14229-1:2013."""

REQUEST_FILE_TRANSFER_2020 = Service(request_sid=RequestSID.RequestFileTransfer,
                                     request_structure=(MODE_OF_OPERATION_2020,
                                                        CONDITIONAL_REQUEST_CONTINUATION_2020),
                                     response_structure=(MODE_OF_OPERATION_2020,
                                                         CONDITIONAL_RESPONSE_CONTINUATION_2020))
"""Translator for :ref:`RequestFileTransfer <knowledge-base-service-request-file-transfer>` service
compatible with ISO 14229-1:2020."""

REQUEST_FILE_TRANSFER = REQUEST_FILE_TRANSFER_2020
"""Default translator for :ref:`RequestFileTransfer <knowledge-base-service-request-file-transfer>` service."""
