"""Definition of UDS translators."""

__all__ = ["BASE_TRANSLATOR", "BASE_TRANSLATOR_2020", "BASE_TRANSLATOR_2013"]

from .service_definitions import (
    ACCESS_TIMING_PARAMETER_2013,
    AUTHENTICATION,
    CLEAR_DIAGNOSTIC_INFORMATION_2013,
    CLEAR_DIAGNOSTIC_INFORMATION_2020,
    COMMUNICATION_CONTROL,
    CONTROL_DTC_SETTING,
    DIAGNOSTIC_SESSION_CONTROL,
    DYNAMICALLY_DEFINE_DATA_IDENTIFIER_2013,
    DYNAMICALLY_DEFINE_DATA_IDENTIFIER_2020,
    ECU_RESET,
    INPUT_OUTPUT_CONTROL_BY_IDENTIFIER_2013,
    INPUT_OUTPUT_CONTROL_BY_IDENTIFIER_2020,
    LINK_CONTROL,
    READ_DATA_BY_IDENTIFIER_2013,
    READ_DATA_BY_IDENTIFIER_2020,
    READ_DATA_BY_PERIODIC_IDENTIFIER,
    READ_DTC_INFORMATION_2013,
    READ_DTC_INFORMATION_2020,
    READ_MEMORY_BY_ADDRESS,
    READ_SCALING_DATA_BY_IDENTIFIER_2013,
    READ_SCALING_DATA_BY_IDENTIFIER_2020,
    REQUEST_DOWNLOAD,
    REQUEST_FILE_TRANSFER_2013,
    REQUEST_FILE_TRANSFER_2020,
    REQUEST_TRANSFER_EXIT,
    REQUEST_UPLOAD,
    RESPONSE_ON_EVENT_2013,
    RESPONSE_ON_EVENT_2020,
    ROUTINE_CONTROL,
    SECURED_DATA_TRANSMISSION_2013,
    SECURED_DATA_TRANSMISSION_2020,
    SECURITY_ACCESS,
    TESTER_PRESENT,
    TRANSFER_DATA,
    WRITE_DATA_BY_IDENTIFIER_2013,
    WRITE_DATA_BY_IDENTIFIER_2020,
    WRITE_MEMORY_BY_ADDRESS,
)
from .translator import Translator

BASE_TRANSLATOR_2013 = Translator(services={
    # Diagnostic and Communication Management functional unit
    DIAGNOSTIC_SESSION_CONTROL,
    ECU_RESET,
    SECURITY_ACCESS,
    COMMUNICATION_CONTROL,
    TESTER_PRESENT,
    ACCESS_TIMING_PARAMETER_2013,
    SECURED_DATA_TRANSMISSION_2013,
    CONTROL_DTC_SETTING,
    RESPONSE_ON_EVENT_2013,
    LINK_CONTROL,
    # Data Transmission functional unit
    READ_DATA_BY_IDENTIFIER_2013,
    READ_MEMORY_BY_ADDRESS,
    READ_SCALING_DATA_BY_IDENTIFIER_2013,
    READ_DATA_BY_PERIODIC_IDENTIFIER,
    DYNAMICALLY_DEFINE_DATA_IDENTIFIER_2013,
    WRITE_DATA_BY_IDENTIFIER_2013,
    WRITE_MEMORY_BY_ADDRESS,
    # Stored Data Transmission functional unit
    CLEAR_DIAGNOSTIC_INFORMATION_2013,
    READ_DTC_INFORMATION_2013,
    # InputOutput Control functional unit
    INPUT_OUTPUT_CONTROL_BY_IDENTIFIER_2013,
    # Routine functional unit
    ROUTINE_CONTROL,
    # Upload Download functional unit
    REQUEST_DOWNLOAD,
    REQUEST_UPLOAD,
    TRANSFER_DATA,
    REQUEST_TRANSFER_EXIT,
    REQUEST_FILE_TRANSFER_2013,
})
"""Base translator for messages compatible with ISO 14229-1:2013."""

BASE_TRANSLATOR_2020 = Translator(services={
    # Diagnostic and communication management functional unit
    DIAGNOSTIC_SESSION_CONTROL,
    ECU_RESET,
    SECURITY_ACCESS,
    COMMUNICATION_CONTROL,
    AUTHENTICATION,
    TESTER_PRESENT,
    CONTROL_DTC_SETTING,
    RESPONSE_ON_EVENT_2020,
    LINK_CONTROL,
    # Data transmission functional unit
    READ_DATA_BY_IDENTIFIER_2020,
    READ_MEMORY_BY_ADDRESS,
    READ_SCALING_DATA_BY_IDENTIFIER_2020,
    READ_DATA_BY_PERIODIC_IDENTIFIER,
    DYNAMICALLY_DEFINE_DATA_IDENTIFIER_2020,
    WRITE_DATA_BY_IDENTIFIER_2020,
    WRITE_MEMORY_BY_ADDRESS,
    # Stored data transmission functional unit
    CLEAR_DIAGNOSTIC_INFORMATION_2020,
    READ_DTC_INFORMATION_2020,
    # InputOutput control functional unit
    INPUT_OUTPUT_CONTROL_BY_IDENTIFIER_2020,
    # Routine functional unit
    ROUTINE_CONTROL,
    # Upload download functional unit
    REQUEST_DOWNLOAD,
    REQUEST_UPLOAD,
    TRANSFER_DATA,
    REQUEST_TRANSFER_EXIT,
    REQUEST_FILE_TRANSFER_2020,
    # Security sub-layer definition
    SECURED_DATA_TRANSMISSION_2020,
})
"""Base translator for messages compatible with ISO 14229-1:2020."""

BASE_TRANSLATOR = BASE_TRANSLATOR_2020
"""Base translator for the newest ISO 14229 version."""
